Repository UnBArqDsw2020-2/2020.2_G4, pull requests merged in 2021-03, with the labels that each got.

#37 #36 - Estrutura do pages
  docs/modelagem/diagramaDER.md
  docs/modelagem/dinamicos/diagramaAtividades.md
  docs/modelagem/dinamicos/diagramaComunicacao.md
  docs/modelagem/dinamicos/diagramaEstado.md
  docs/modelagem/dinamicos/diagramaSequencia.md
  docs/modelagem/dinamicos/diagramacasoUso.md
  docs/modelagem/estaticos/diagramaClasses.md
  docs/modelagem/estaticos/diagramaComponentes.md
  docs/modelagem/estaticos/diagramaPacotes.md
  mkdocs.yml
Labels: Estrutural

#43 Diagrama comunicacao
  docs/modelagem/dinamicos/diagramaComunicacao.md
  docs/modelagem/dinamicos/diagramaComunicacao/diagrama-comunicacao-comprar.jpg
Labels: Documentação, Modularização

#44 Diagrama pacotes
  docs/modelagem/estaticos/diagramaPacotes.md
  docs/modelagem/estaticos/diagramaPacotes/diagrama-pacotes-geral.jpg
Labels: Documentação, Modularização

#46 Diagrama sequencia
  docs/modelagem/dinamicos/diagramaSequencia.md
Labels: Documentação

#48 Backlog
  docs/base/elicitacao/priorizacao/Moscow.md
  mkdocs.yml
Labels: Documentação, Elicitação
